version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    reviewers:
      - glitchcrab
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - glitchcrab
