name: conventional commits enforcer
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: webiny/action-conventional-commits@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
