name: Release drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
