name: 'build binary'
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: 'Build binary and test'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v6
      - name: 'setup go'
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: 'build binary'
        run: go build -o sonar
      - name: 'create kind cluster'
        uses: helm/kind-action@v1
        with:
          cluster_name: 'sonar-test'
      - name: 'test deploying with sonar'
        run: ./sonar create -n default -N ci-test -i glitchcrab/ubuntu-debug
      - name: 'wait for deployment to start'
        uses: jupyterhub/action-k8s-await-workloads@v3
        with:
          workloads: "deploy/sonar-ci-test"
          namespace: "default"
          timeout: 60
      - name: 'test teardown with sonar'
        run: ./sonar destroy -n default -N ci-test -f
